#!/usr/bin/env bash

if [[ -v DEPLOY_USER ]]; then
  deployuser="$DEPLOY_USER"
else
  deployuser="$(whoami)"
fi

args=()
provided_hosts=()
for arg in "$@"; do
  if [[ "$arg" == --* ]]; then
    args+=("$arg")
  else
    provided_hosts+=("$arg")
  fi
done

hosts=()
for host in "${provided_hosts[@]}"; do
  host="$(basename -- "$host")"

  if [ -n "$host" ]; then
    hosts+=(".#$host")
  fi
done

for host in "${hosts[@]}"; do
  set -x
  deploy "${args[@]}" \
    --auto-rollback false --magic-rollback false --rollback-succeeded false \
    --skip-checks --interactive-sudo true --ssh-user "$deployuser" \
    "${host}" -- -L
done
